###
POST http://localhost:5005/api/peliculas HTTP/1.1
Content-Type: application/json

{
    "nombre": "Spiderman",
    "tarifa": "A",
    "hora_inicio": "15:00",
    "idioma": "Espanol",
    "tipo": "2D",
    "categoria": "Accion",
    "restriccion": "NA",
    "imagen": "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg"
}

###
POST http://localhost:5005/api/peliculas HTTP/1.1
Content-Type: application/json

{
    "nombre": "Spiderman",
    "tarifa": "A",
    "hora_inicio": "15:00",
    "idioma": "Espanol",
    "tipo": "2D",
    "categoria": "Accion",
    "restriccion": "NA",
    "imagen": "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg"
}

###
GET http://localhost:5005/api/peliculas HTTP/1.1

###
GET http://localhost:5005/api/peliculas/634e2aff658c7da3a5174b5d HTTP/1.1

###
PUT  http://localhost:5005/api/peliculas/634e2aff658c7da3a5174b5d HTTP/1.1
Content-Type: application/json

{
    "nombre": "Spiderman",
    "tarifa": "A",
    "hora_inicio": "15:00",
    "idioma": "Espanol",
    "tipo": "2D",
    "categoria": "Accion",
    "restriccion": "NA",
    "imagen": "https://upload.wikimedia.org/wikipedia/en/f/f9/Spider-Man_Homecoming_poster.jpg"
}

###
DELETE http://localhost:5005/api/peliculas/634e2aff658c7da3a5174b5d HTTP/1.1